services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env.docker
    ports:
      - 5432:5432
    networks:
      - minglenet
  core:
    build: /core/
    env_file:
      - .env.docker
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - minglenet

  app:
    build: /mingle/
    ports:
      - 5173:5173
    depends_on:
      - core
    networks:
      - minglenet

    
networks:
  minglenet:
    name: mingle-net